[Rule]
# > 指定直连
RULE-SET,https://raw.githubusercontent.com/csshan1/surge-rules/main/rules/Direct.list,DIRECT

# > 智能助理
RULE-SET,https://raw.githubusercontent.com/csshan1/surge-rules/main/rules/OpenAI.list,Intelligence

# > 苹果服务
RULE-SET,https://raw.githubusercontent.com/csshan1/surge-rules/main/rules/Apple.list,Apple

# > GitHub
RULE-SET,https://raw.githubusercontent.com/csshan1/surge-rules/main/rules/GitHub.list,Proxy,no-resolve

# > 微软服务
RULE-SET,https://raw.githubusercontent.com/csshan1/surge-rules/main/rules/Microsoft.list,Microsoft

# > 社交平台
RULE-SET,https://raw.githubusercontent.com/csshan1/surge-rules/main/rules/Telegram.list,Telegram

# > 游戏平台
RULE-SET,https://raw.githubusercontent.com/csshan1/surge-rules/main/rules/Epic.list,Gamer
RULE-SET,https://raw.githubusercontent.com/csshan1/surge-rules/main/rules/Sony.list,Gamer
RULE-SET,https://raw.githubusercontent.com/csshan1/surge-rules/main/rules/Steam.list,Gamer
RULE-SET,https://raw.githubusercontent.com/csshan1/surge-rules/main/rules/Nintendo.list,Gamer

# > 流媒体
RULE-SET,https://raw.githubusercontent.com/csshan1/surge-rules/main/rules/YouTube.list,YouTube
RULE-SET,https://raw.githubusercontent.com/csshan1/surge-rules/main/rules/Netflix.list,Netflix
RULE-SET,https://raw.githubusercontent.com/csshan1/surge-rules/main/rules/Disney.list,Disney+
RULE-SET,https://raw.githubusercontent.com/csshan1/surge-rules/main/rules/Spotify.list,Spotify
RULE-SET,https://raw.githubusercontent.com/csshan1/surge-rules/main/rules/TikTok.list,TikTok
RULE-SET,https://raw.githubusercontent.com/csshan1/surge-rules/main/rules/BiliBili.list,BiliBili
RULE-SET,https://raw.githubusercontent.com/csshan1/surge-rules/main/rules/ChinaMedia.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/csshan1/surge-rules/main/rules/GlobalMedia.list,GlobalMedia

# > Proxy
RULE-SET,https://raw.githubusercontent.com/csshan1/surge-rules/main/rules/Proxy.list,Proxy,extended-matching

# > China
RULE-SET,https://raw.githubusercontent.com/csshan1/surge-rules/main/rules/ChinaMax.list,DIRECT,extended-matching

# > 局域网地址
RULE-SET,LAN,DIRECT

# > DNS 查询失败走Final规则
FINAL,Proxy,dns-failed
